---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "National Teen Pregnancy Prevention Month"
keywords:    "National Teen Pregnancy Prevention Month"
description: "In May, the Family and Youth Services Bureau’s Adolescent Pregnancy Prevention Program will observe Teen Pregnancy Prevention Month by raising awareness and sharing resources."
source_link: "http://teenpregnancy.acf.hhs.gov"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-7681736-4 ## put YOUR key here to enable tracking! (blank to disable)
